### ISSUE TITLE
node.enabled property is string not Boolean

### ISSUE THREAD

**Issue by NickWaterton** [shbatm/PyISY#12]
When parsing the initial node data in `Nodes.parse` the line
```
enabled = value_from_xml(feature, "enabled")
```
returns a string `'true'` or `'false'` when I believe this is intended to be a Boolean value.
later in the Node class, this is how `self._enabled` is initialized:
```
self._enabled = enabled if enabled is not None else True
```
So this would end up as a mixed type if enabled was not passed in the constructor.

**Comment by shbatm** [comment]
Thanks! Should be fixed in the latest PyISY_beta release.
