### ISSUE TITLE
Node state is not Correct  after Communication Error

### ISSUE THREAD

**Issue by NickWaterton** [shbatm/PyISY#15]
I ran into a problem with `auto_update` enabled.

If I send a command to a device (eg `on()`), but there is a communication error between the ISY and the device, the node status is still updated as if the command  was successful. No error message is given, and everything continues normally, except the node state is now incorrect (ie the node is `on` but the actual device is off). This is never corrected.

The problem seems to be in `NodeBase`, where at the end of the command this is run:
```
# Calculate hint to use if status is updated
        hint = None
        if cmd in ["DON", "DFON"]:
            hint = val if val is not None else 255
        if cmd in ["DOF", "DFOF"]:
            hint = 0

        self.update(UPDATE_INTERVAL, hint=hint)
```
in the `Node` update is:
```
def update(self, wait_time=0, hint=None, xmldoc=None):
        """Update the value of the node from the controller."""
        if not self.isy.auto_update and not xmldoc:
            sleep(wait_time)
            req_url = self.isy.conn.compile_url(
                ["nodes", self._id, ATTR_GET, STATE_PROPERTY]
            )
            xml = self.isy.conn.request(req_url)
            try:
                xmldoc = minidom.parseString(xml)
            except:
                self.isy.log.error("%s: Nodes", XML_PARSE_ERROR)
                return
        elif hint is not None:
            # assume value was set correctly, auto update will correct errors
            self.status.update(hint, silent=True)
            self.isy.log.debug("ISY updated node: %s", self._id)
            return
.
.
.
```
so with `auto_update`  `True` and the command `DON`, what happens is that `self.status.update(hint, silent=True)` is executed, updating the state of the Node, irrespective of what happens to the actual device.

The comment is `auto update will correct errors` but this is not the case. unless the node is queried at some future time, the incorrect status will never be corrected, and this assumes that the communication error goes away.

BTW I am getting communication errors, I'm assuming because I'm sending commands to multiple devices too fast. Which may or may not be another issue.

As a fix I have removed `not self.isy.auto_update and ` from `Node` `update`, and the status seems to being queried each time now. I have not had any communication errors since making this change, so it remains to be seen what happens if i do. I will update when/if it happens.

**Comment by shbatm** [comment]
Interesting. Can you share what's being reported in the communication errors? The ISY has some known issues with command floods but you're right, the node status should be getting reverted if the command fails.

From why I understand the whole hint mechanism is to make the module more responsive to changes--it assumes the call is going to succeed and updates the node accordingly and expects that if the ISY reports back an error or fails the command the status will be reverted.  This is an original behavior.

@rmkraus or @overloadut -- have you seen any similar issues before? Just trying to make sure this isn't something I broke with my updates.

**Comment by shbatm** [comment]
Also just to be clear -- the communication errors are between the ISY and the end device--correct? Not between the PyISY module and the ISY?

**Comment by NickWaterton** [comment]
> Also just to be clear -- the communication errors are between the ISY and the end device--correct? 

Yes, this is correct.
It looks like original behavior, I think this code has been in there for a long time.

I can't really show you anything from the logs - there is nothing in there to indicate an error, so I can't tell working ON/OFF event's from failed ones. They look the same. The only time you get an error is if you actually QUERY the insteon device - which the library never does with `auto_update` enabled. The only actual QUERY is at start up.

The only reason I know there is an error is the ISY Console pops up a message "Error communicating with device xxx" and puts `!` next to the device. Plus the light does not go ON of course. You can get control back by clicking on `query` from the ISY console, and the device comes back to normal.

What I'm doing is that I have a master switch cross linked to two LED panels (controlled by two insteon ballast controllers). When you send an ON to the master switch, the LED Panels do not go on (as is the usual case with Insteon direct commands), so I have a routine that watches the master switch, and when it sees it turn ON, sends an ON to both LED panels (same for OFF or a dimmer level).

The result is that when you send ON to the master switch, you immediately get two more ON's sent to the LED panels. one of these was failing (not always) with the communication error. I'm assuming this is because of the speed that all the ON's are sent. The ON is actually sent by a motion detector.

The problem is that PyISY acts as though the command was successful, and continues as normal, assuming the LED panels are ON, when in fact one of them is not. There is no error logged, and the state of the LED Panel never gets corrected. You have to QUERY the state of the Panels to get the actual state.

This does slow down the response of the library slightly, but in my mind it's better to be accurate than fast.

**Comment by NickWaterton** [comment]
OK, so I've run some tests with the original code. This is using a plug in Siren module (as i can't unplug my LED Panels).

If I unplug the module after PyISY has initialized (simulate a communication error) I, and then send an ON I get this:

```
[I 2019-11-06 13:57:53,974] (Main                ) ISY Request: http://192.168.100.45:80/rest/nodes/3F%203C%201%201/cmd/DON
[D 2019-11-06 13:57:53,987] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="200" sid="uuid:49"><control>_5</control><action>1</action><node></node><eventInfo></eventInfo></Event>
[D 2019-11-06 13:57:54,003] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="201" sid="uuid:49"><control>_5</control><action>0</action><node></node><eventInfo></eventInfo></Event>
[D 2019-11-06 13:57:54,007] (Main                ) ISY Response Recieved
[I 2019-11-06 13:57:54,008] (Main                ) ISY command on sent to 3F 3C 1 1.
[I 2019-11-06 13:57:54,010] (Main                ) Node: 3F 3C 1 1 (hallwaySiren.1 Siren Trigger) changed to 255 (status:255 scaled:ON)
[D 2019-11-06 13:57:54,010] (Main                ) ISY updated node: 3F 3C 1 1
[I 2019-11-06 13:57:54,011] (Main                ) publishing: /isy_status/hallwaySiren.1 Siren Trigger ON (UOM:byte)
[D 2019-11-06 13:58:10,283] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="202" sid="uuid:49"><control>_0</control><action>120</action><node></node><eventInfo></eventInfo></Event>
[D 2019-11-06 13:58:10,284] (Main                ) ISY HEARTBEAT: 2019-11-06T13:58:10.283949
[D 2019-11-06 13:58:18,985] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="203" sid="uuid:49"><control>ERR</control><action>1</action><node>3F 3C 1 1</node><eventInfo></eventInfo></Event>
[I 2019-11-06 13:58:18,986] (Main                ) Node 3F 3C 1 1 (hallwaySiren.1 Siren Trigger) received event ERR(device_communication_errors), value: 1, uom: (unknown)
[D 2019-11-06 13:58:18,987] (Main                ) Unhandled event: ERR
[I 2019-11-06 13:58:18,987] (Main                ) publishing: /isy_status/hallwaySiren.1 Siren Trigger/ERR 1 (UOM:(unknown))
[D 2019-11-06 13:58:18,988] (Main                ) ISY Node Control Event: 3F 3C 1 1 ERR 1
[D 2019-11-06 13:58:18,989] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="204" sid="uuid:49"><control>_3</control><action>NE</action><node>3F 3C 1 1</node><eventInfo></eventInfo></Event>
[D 2019-11-06 13:58:18,992] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="205" sid="uuid:49"><control>_1</control><action>3</action><node></node><eventInfo>[   3F 3C 1 1]      ERR   1</eventInfo></Event>
[D 2019-11-06 13:58:35,281] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="206" sid="uuid:49"><control>_0</control><action>120</action><node></node><eventInfo></eventInfo></Event>
[D 2019-11-06 13:58:35,282] (Main                ) ISY HEARTBEAT: 2019-11-06T13:58:35.282374
```
So the state of the node gets updated immediately to ON (even though the siren is unplugged), then a few seconds later I get the "Communications error" from the ISY Console, and the Error is logged, but the node state is never updated. It just looks like everything worked, and the Siren is ON.

There is 20 seconds between sending the ON, and getting the Error logged. I could trap the error and retry, but 20 seconds is a long time to just assume everything is OK.

If I do it again, with the modified code, I get this:
```
[D 2019-11-06 14:09:50,222] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="206" sid="uuid:50"><control>_0</control><action>120</action><node></node><eventInfo></eventInfo></Event>
[D 2019-11-06 14:09:50,223] (Main                ) ISY HEARTBEAT: 2019-11-06T14:09:50.222990
[I 2019-11-06 14:09:55,654] (Main                ) MQTT message received topic: /isy_command/hallwaySiren.1 Siren Trigger value:b'ON'
[I 2019-11-06 14:09:55,658] (Main                ) ISY Request: http://192.168.100.45:80/rest/nodes/3F%203C%201%201/cmd/DON
[D 2019-11-06 14:09:55,670] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="207" sid="uuid:50"><control>_5</control><action>1</action><node></node><eventInfo></eventInfo></Event>
[D 2019-11-06 14:09:55,686] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="208" sid="uuid:50"><control>_5</control><action>0</action><node></node><eventInfo></eventInfo></Event>
[D 2019-11-06 14:09:55,690] (Main                ) ISY Response Recieved
[I 2019-11-06 14:09:55,691] (Main                ) ISY command on sent to 3F 3C 1 1.
[I 2019-11-06 14:09:56,192] (Main                ) ISY Request: http://192.168.100.45:80/rest/nodes/3F%203C%201%201/get/ST
[D 2019-11-06 14:09:56,204] (Main                ) ISY Response Recieved
[D 2019-11-06 14:09:56,205] (Main                ) ISY updated node: 3F 3C 1 1
[D 2019-11-06 14:10:15,219] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="209" sid="uuid:50"><control>_0</control><action>120</action><node></node><eventInfo></eventInfo></Event>
[D 2019-11-06 14:10:15,220] (Main                ) ISY HEARTBEAT: 2019-11-06T14:10:15.220678
[D 2019-11-06 14:10:20,673] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="210" sid="uuid:50"><control>ERR</control><action>1</action><node>3F 3C 1 1</node><eventInfo></eventInfo></Event>
[I 2019-11-06 14:10:20,674] (Main                ) Node 3F 3C 1 1 (hallwaySiren.1 Siren Trigger) received event ERR(device_communication_errors), value: 1, uom: (unknown)
[D 2019-11-06 14:10:20,674] (Main                ) Unhandled event: ERR
[I 2019-11-06 14:10:20,675] (Main                ) publishing: /isy_status/hallwaySiren.1 Siren Trigger/ERR 1 (UOM:(unknown))
[D 2019-11-06 14:10:20,676] (Main                ) ISY Node Control Event: 3F 3C 1 1 ERR 1
[D 2019-11-06 14:10:20,677] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="211" sid="uuid:50"><control>_3</control><action>NE</action><node>3F 3C 1 1</node><eventInfo></eventInfo></Event>
[D 2019-11-06 14:10:20,679] (Main                ) ISY Update Received:
<?xml version="1.0"?><Event seqnum="212" sid="uuid:50"><control>_1</control><action>3</action><node></node><eventInfo>[   3F 3C 1 1]      ERR   1</eventInfo></Event>
```
So it still doesn't work (Siren is unplugged), but instead of the node updating to ON, I get the same error logged, the difference being that the node states in now not updated with an incorrect value. I'm not saying this is a fix, it's jut better than having the command feeding back as successful, and not finding out until 20 seconds later that it wasn't, and never gets corrected.

**Comment by shbatm** [comment]
> What I'm doing is that I have a master switch cross linked to two LED panels (controlled by two insteon ballast controllers). When you send an ON to the master switch, the LED Panels do not go on (as is the usual case with Insteon direct commands), so I have a routine that watches the master switch, and when it sees it turn ON, sends an ON to both LED panels (same for OFF or a dimmer level).

This sounds like an odd use case. Why are you not using scenes for this control and sending a command to the scene instead of the individual switch?

> The problem is that PyISY acts as though the command was successful, and continues as normal, assuming the LED panels are ON, when in fact one of them is not. The state of the LED Panel never gets corrected. You have to QUERY the state of the Panels to get the actual state.

The base logic for using the event stream and auto_update is to assume successful communications and revert if something fails. I would support adding some logic to force a re-query in response to an ERR command received in the event stream but re-querying after every command seems to contradict the whole point of using the auto_update and could create some race-conditions where the query response is sent before the device changes and you still get false statuses.

> There is 20 seconds between sending the ON, and getting the Error logged. I could trap the error and retry, but 20 seconds is a long time to just assume everything is OK.

The 20 sec delay for the ERR response seems long to me--was this with this version of the code or the original PyISY? There were some issues with delayed log messages in the original PyISY, but I thought those were fixed in the latest version.  

Also, just curious: if you're on ISYv5 have you tried upping the number of retries for those devices to eliminate the errors?

**Comment by NickWaterton** [comment]
> This sounds like an odd use case. Why are you not using scenes for this control and sending a command to the scene instead of the individual switch?

I could, but then this is another control to set up. Right now I'm migrating from a setup that used direct PLM commands to one using the ISY (for various reasons, mostly the PLM code is obsolete, written in java, and hard to fix).

I understand the speed issue, and up to now with the direct PLM interface I'm using, you just send the command and it works, no query needed. I was hoping the ISY would be as reliable.

> Also, just curious: if you're on ISYv5 have you tried upping the number of retries for those devices to eliminate the errors?

This is a good point (I am on 5.x), I did find that the problematic devices would not let me access the PLM communication menu. Querying the Insteon Engine fixed that, and also fixed the communication failures (at least I haven't had one since on that device). As my ISY set up is quite new, it's possible the devices aren't quite configured right.

I'm reverting to the original code, checking the Inseton engine is right for problem devices, and I have implemented a queuing system that spaces commands out by 100mS, so that I don't send them too fast (in case that is a thing).

The biggest problem is the 20s delay before an error is reported if there is a problem. That seems to be coming from the ISY - when there is an error, it pops open several dialog boxes before giving the error pop-up, at the same time as the error appears in the PyISY log.

I'm nearly finished moving over from the old system, I'll see how it goes when I'm done.

**Comment by shbatm** [comment]
> I could, but then this is another control to set up. Right now I'm migrating from a setup that used direct PLM commands to one using the ISY (for various reasons, mostly the PLM code is obsolete, written in java, and hard to fix).
> 
> I understand the speed issue, and up to now with the direct PLM interface I'm using, you just send the command and it works, no query needed. I was hoping the ISY would be as reliable.

I would recommend looking into adding the scenes. The big advantage being it's 1 single command sent to the Insteon network from the modem vs 1 for every device (because the scenes are hard-coded in the devices themselves).  And there's lots of room for multiple scenes, so you can add several.

I've been using the ISY for 6 years and on ~40 devices; with the exception of a failed modem power supply and a dead keypad relay, I rarely see any communication errors on the network.

**Comment by OverloadUT** [comment]
Just tossing in a huge +1 for using scenes for the use-case you explained. Scenes are explicitly for that purpose and strongly recommended by Insteon.

**Comment by NickWaterton** [comment]
The problem is that you can only set a scene on or off. I can't send a dimmer level, and the ceiling panels are dimmers.

So, yes, I can use a scene to turn them both 100% ON or OFF, but I can't set a dimmer level via a scene.

So I have a switch (dimmer) and two ceiling panels (dimmers). I can turn them all on or off with a scene, but what if I want to set them to 50%? I have to send individual insteon commands to each device to set them to 50% brightness.. Cannot do this via a scene. I can send `dim` or `brighten` commands to a scene, but I can't send a direct brightness level.

The only way to keep everything synchronized is to have a routine that copies the settings from one device to another via individual Insteon commands. Which is three commands for three devices (switch and two panels), but if one panel doesn't respond, the whole thing messes up.

I can use a scene to turn everything ON or OFF via the motion detector (as i do want them 100% on then), but then I have a 4th control to keep synchronized.

**Comment by shbatm** [comment]
Fair enough regarding the dimming. 

Another potential option for you if you're controlling them programmatically and want to increase reliability, would be to have multiple scenes with various on levels (e.g. 10%, 25%, 50%, 75%, 100%, etc.) and call the one closest to the brightness you want for that scenario.

**Comment by NickWaterton** [comment]
I thought of that, but I have five other similar set ups (with multiple lights controlled by one switch/dimmer) and it all seems like too much work.

Fortunately with my 100ms delay in the loop, everything seems to be working fine, it's just the odd failure on this basement panel that's bugging me. Not sure why this one is being a pain. Anyway I did switch the basement panels to an ON/OFF scene for the motion sensor, so I'll see if that improves reliability.

**Comment by shbatm** [comment]
No plans to handle communication error checking within PyISY at this time. Closing for now.
