### ISSUE TITLE
error getting the list of programs when it's (nearly) empty

### ISSUE THREAD

**Issue by arrowstem** [shbatm/PyISY#18]
I'm having an issue with pyisy-beta-2.0.0.dev151. I'm running my script with Python3.7 under ubuntu. Also, node update doesn't work; I'm not sure if this a related issue or a separate one. The essential code lines are 
```
isy_conn = pyisy.ISY(ADDR,PORT,USER,PASS,HTTPS,TLS,log)
node_therm = isy_conn.nodes['Thermostat']
node_therm.update()
```
The output is
```
Bad ISY Request: https://my.isy.io:443/rest/vars/definitions/1 404: retry #0
Bad ISY Request: https://my.isy.io:443/rest/vars/definitions/1 404: retry #1
Bad ISY Request: https://my.isy.io:443/rest/vars/definitions/1 404: retry #2
Bad ISY Request: https://my.isy.io:443/rest/vars/definitions/1 404: retry #3
Bad ISY Request: https://my.isy.io:443/rest/vars/definitions/1 404: retry #4
Bad ISY Request: https://my.isy.io:443/rest/vars/definitions/1 404: retry #5
Bad ISY Request: https://my.isy.io:443/rest/vars/definitions/1 404: Failed after 5 retries
ISY Could not parse response, poorly formatted XML.: Variables
ISY could not update node: ZW006_1
```
The file programs.xml (zipped here: [programs.zip](https://github.com/shbatm/PyISY/files/4398338/programs.zip)) is apparently (nearly) empty. I didn't create it by hand and I'd expect it to be processed somehow. Was the failure to parse it the reason why ISY could not update a node?

**Comment by shbatm** [comment]
It does look like it's failing to parse Variables and Programs on the initial connection, which is probably why it's failing... It should gracefully move on if you don't have any programs or variables defined, but it looks like something is causing it to die.

For programs it looks like none have ever been run which is probably the issue there. I'll work on handling that issue, but as a workaround I'd create and run at least one program (usually UDI recommends querying all nodes at 3am, that'd be a good one to add, search their site/forum for details) 

Do you have any state and integer variables defined (at least one of each)? This is probably the issue with variables. Again, I'll fix the error handling, but a workaround is to just make sure you have 1 of each type saved.

If you don't mind, send your xml files from here:

- https://my.isy.io:443/rest/vars/definitions/1 
- https://my.isy.io:443/rest/vars/definitions/2

**Comment by shbatm** [comment]
I have not been able to duplicate this error from your comment on automicus/PyISY#82:

> Traceback (most recent call last):
> 
>   File "[path]\isy_interface.py", line 46, in <module>
>     isy_conn = pyisy.ISY(ADDR,PORT,USER,PASS,HTTPS,TLS,log)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\isy.py", line 81, in __init__
>     self.programs = Programs(self, xml=self.conn.get_programs())
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\__init__.py", line 95, in __init__
>     self.parse(xml)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\__init__.py", line 260, in parse
>     pobj = Program(self, address, pname, **data)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\pyisy\programs\program.py", line 75, in __init__
>     super().__init__(programs, address, pname, pstatus)
> 
> TypeError: super(type, obj): obj must be an instance or subtype of type

I was able to use your ISY's Program.xml file and it parsed fine:

```shell
2020-03-29 07:26:47 INFO [__main__] ISY connected: True
2020-03-29 07:26:47 DEBUG [__main__] <?xml version="1.0" encoding="UTF-8"?><programs><program id="0001" status="true" folder="true"><name>My Programs</name><lastRunTime></lastRunTime><lastFinishTime></lastFinishTime></program><program id="0002" parentId="0001" status="false" folder="false" enabled="true" runAtStartup="false" running="idle"><name>New Program</name><lastRunTime></lastRunTime><lastFinishTime></lastFinishTime></program></programs>
2020-03-29 07:26:47 INFO [__main__] ISY Loaded/Updated Programs
2020-03-29 07:26:47 DEBUG [__main__] Folder <root>
  + My Programs: Folder(0001)
  |     New Program: Program(0002)
  |
  -
```
So I'm not sure what's going on there.

Still looking at the variables. I think I know what that issue is.

**Comment by shbatm** [comment]
Please try `pyisy-beta==2.0.0.dev153` when you have a chance to test the Variable issue. It'd still be better if you define at least 1 variable of each type so you don't get the bad request errors, but at least this version should continue on if you don't have one of each.

**Comment by arrowstem** [comment]
Before I followed your advice to define the variables, I installed dev153 version and ran it under Ubuntu via Python 3.7. Here's what I've got:
```
Bad ISY Request: https://my.isy.io:443/rest/vars/definitions/1
ISY Could not parse variables, poorly formatted XML.
```
Indeed https://my.isy.io:443/rest/vars/definitions/1 gives `/CONF/INTEGER.VAR not found` and https://my.isy.io:443/rest/vars/definitions/2 gives 
```
<CList type="VAR_INT">
<e id="1" name="State_1"/>
<e id="2" name="State_2"/>
<e id="3" name="State_3"/>
</CList>
```
Just to remind, version 151 printed `ISY could not update node: ZW006_1` when trying to do
```
    node_therm = isy_conn.nodes['Thermostat']
    node_therm.update()
```
Version 153 didn't print that, but I don't think the update worked because `print(node_therm.aux_properties)` produced the list of only 3 variables as before:
```
[{'id': 'CLIMD', 'prec': '0', 'uom': ['67'], 'value': 3},
 {'id': 'CLISPC', 'prec': '0', 'uom': ['17'], 'value': 75},
 {'id': 'CLISPH', 'prec': '0', 'uom': ['17'], 'value': 72}]
```
If I don't do `update()`, the output is exactly the same.

**Comment by arrowstem** [comment]
We added a variable and a program to our ISY. Now I'm getting a more complete list of aux_properties. Perhaps the reason it wasn't updated before was linked to the absence of the variables and/or programs. I used to get only 3 variables on the list of aux_properties, now it's as shown below:
```
  {'CLIFRS': {'control': 'CLIFRS',
              'formatted': 'Off',
              'prec': '0',
              'uom': '80',
              'value': '0'},
   'CLIFS': NodeProperty('CLIFS': value='0' prec='0' uom='68' formatted='Auto'),
   'CLIFSO': {'control': 'CLIFSO',
              'formatted': 'No Override',
              'prec': '0',
              'uom': '81',
              'value': '0'},
   'CLIHCS': {'control': 'CLIHCS',
              'formatted': 'Idle',
              'prec': '0',
              'uom': '66',
              'value': '0'},
   'CLIMD': NodeProperty('CLIMD': value='3' prec='0' uom='67' formatted='Auto'),
   'CLISPC': {'control': 'CLISPC',
              'formatted': '75°F',
              'prec': '0',
   'CLISPH': {'control': 'CLISPH',
              'formatted': '72°F',
              'prec': '0',
              'uom': '17',
              'value': '72'},
   'ERR': NodeProperty('ERR': value='0' prec='0' uom='' formatted='0')}
```

**Comment by shbatm** [comment]
Great! I've also added some additional checks so that hopefully it handles empty variable lists a little better.

Also, just FYI: you can translate the command names to something more user friendly with the `COMMAND_FRIENDLY_NAME` dictionary. An example would be like this:

```python
    from pyisy.constants import COMMAND_FRIENDLY_NAME

    for key, value in isy.nodes["25 1A 84 1"].aux_properties.items():
        _LOGGER.info("%s: %s", COMMAND_FRIENDLY_NAME.get(key), value)
```

Results in:

```shell
2020-03-31 05:14:26 INFO [__main__] climate_mode: NodeProperty('CLIMD': value='2' prec='0' uom='98' formatted='Cool')
2020-03-31 05:14:26 INFO [__main__] cool_setpoint: NodeProperty('CLISPC': value='146' prec='0' uom='101' formatted='73.0°')
2020-03-31 05:14:26 INFO [__main__] heat_setpoint: NodeProperty('CLISPH': value='136' prec='0' uom='101' formatted='68.0°')
2020-03-31 05:14:26 INFO [__main__] humidity: NodeProperty('CLIHUM': value='54' prec='0' uom='22' formatted='54%')
2020-03-31 05:14:26 INFO [__main__] heat_cool_state: NodeProperty('CLIHCS': value='0' prec='0' uom='66' formatted='Idle')
2020-03-31 05:14:26 INFO [__main__] unit_of_measure: NodeProperty('UOM': value='2' prec='0' uom='' formatted='2')
2020-03-31 05:14:26 INFO [__main__] fan_state: NodeProperty('CLIFS': value='8' prec='0' uom='99' formatted='Auto')
```
