### ISSUE TITLE
variable not on COMMAND_FRIENDLY_NAME dictionary

### ISSUE THREAD

**Issue by arrowstem** [shbatm/PyISY#19]
I chanced upon a climate (Thermostat node) variable that is not yet on the COMMAND_FRIENDLY_NAME dictionary, here's it with its value:
```
CLIFRS: NodeProperty('CLIFRS': value='0' prec='0' uom='80' formatted='Off')
```
What is it?

**Comment by shbatm** [comment]
Not sure. Can you browse to https://my.isy.io/rest/config and look through the commands section. It should say there. Let me know and I'll add it.

**Comment by shbatm** [comment]
Nevermind, I found it:

```xml
<name>CLIFRS</name>
<label>Fan Running State</label>
```

Also, to make sure it doesn't choke on an unknown name, you can use `COMMAND_FRIENDLY_NAME.get(key, key)` (if using the example I gave in the other issue). That will try and lookup the friendly name of `key` and if not found, just use `key` as the value, instead of `None`.
