### ISSUE TITLE
cannot get attributes for some nodes

### ISSUE THREAD

**Issue by arrowstem** [shbatm/PyISY#22]
I'm using pyisy v. dev153 under ubuntu. I want to list all node attributes by doing the following:
```
import pyisy as PyISY
import inspect
isy_conn = PyISY.ISY(ADDR,PORT,USER,PASS,HTTPS,TLS,LOG)
for node_name in isy_conn.nodes:
    node_name = node_name.replace('/','')
    node = isy_conn.nodes[node_name]
    attributes = inspect.getmembers(node, lambda a:not(inspect.isroutine(a)))
```
The last command works fine for some of the nodes but fails for some others as the list below shows:

Alexa - success
Auto DR - success
Copier On-Off Power Switch - failed
Dish Washer ZW 003 On-Off Pow - failed
Dryer ZW 010 On-Off Power Swi - failed
Monitor 1 ZW 007.1 on-Off Pow - failed
Monitor 2 ZW 007.2 Energy Met - failed
Monitor 2 ZW 007.2 On-Off Pow - failed
Monitor 3 ZW 007.3 On-Off Pow - failed
Monitors ZW 007 On-Off Power  - failed
Tesla NodeServer - success
Thermostat - success
Washing Machine ZW 002 On-Off - failed
ZW 002 Color Switch - failed
ZW 003 Pulse Meter - failed
ZW 004 Notify Sensor - failed
ZW 006 Energy Meter - success
ZW 007 Pulse Meter - failed
ZW 010 Color Switch - failed
ZW 011 On-Off Power Switch - failed
ZW 011 Water Meter - failed
ZW 016 0.0.0 - failed
ZW 017 0.0.0 - failed

When it fails, the following error is reported:
```
Traceback (most recent call last):
  File "isy_test.py", line 64, in <module>
    attributes = inspect.getmembers(node, lambda a:not(inspect.isroutine(a)))
  File "/usr/lib/python3.7/inspect.py", line 341, in getmembers
    value = getattr(object, key)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pyisy/nodes/node.py", line 178, in is_thermostat
    and any(self.zwave_props.category in THERMOSTAT_ZWAVE_CAT)
TypeError: 'bool' object is not iterable
```
Please advise.

**Comment by shbatm** [comment]
```python
import pyisy as PyISY
import inspect
from types import MethodType

isy_conn = PyISY.ISY(ADDR,PORT,USER,PASS,HTTPS,TLS,LOG)

for (path, node) in isy_conn.nodes:
    properties = [
        name
        for (name, value) in inspect.getmembers(
            type(node), lambda a: isinstance(a, property)
        )
    ]
    attributes = {prop: getattr(node, prop) for prop in properties}
    methods = [
        name
        for (name, value) in inspect.getmembers(
            node, lambda m: isinstance(m, MethodType)
        )
    ]
    print("%s: properties: %s, methods: %s", path, attributes, methods)
```

**Comment by arrowstem** [comment]
Thanks shbatm but I've got an error in
```
Traceback (most recent call last):
  File "isy_test.py", line 42, in <module>
    type(node), lambda a: isinstance(a, property)
  File "/usr/lib/python3.7/inspect.py", line 341, in getmembers
    value = getattr(object, key)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/VarEvents/__init__.py", line 553, in __get__
    return self._data[instance]
  File "/usr/lib/python3.7/weakref.py", line 396, in __getitem__
    return self.data[ref(key)]
TypeError: cannot create weak reference to 'NoneType' object
```
in
```
    properties = [
        name
        for (name, value) in inspect.getmembers(
            type(node), lambda a: isinstance(a, property) # LINE 42
        )
    ]
```

**Comment by arrowstem** [comment]
this happens for ALL `(path, node) in isy_conn.nodes`

**Comment by shbatm** [comment]
Not entirely sure what you're trying to accomplish with this other than what could be done by just printing the various properties you need directly for each node (e.g. `print(node.propertyx)`. The property names are pretty easy to [get from the code](https://github.com/shbatm/PyISY/tree/PyISY_beta/pyisy/nodes) (`Group` and `Node` both inherit/include everything from `NodeBase`)

The above code was working fine for my test script--maybe it needs to be called inside of a function though? 

Try dropping it in the example script around [here](https://github.com/shbatm/PyISY/blob/46b03ff89f5961f5ab88596ceb7f9835830dce0c/examples/connection_test.py#L66) and see if that's the issue.

**Comment by arrowstem** [comment]
I was just trying to get a complete list of properties in one place, and I was puzzled why I can get it for some nodes but not for others. OK, thanks anyway, I guess I'll have figure it out from the class definitions.

**Comment by shbatm** [comment]
Closing due to merge of V2 code upstream. Please open any other issues in automicus/PyISY.
