### ISSUE TITLE
how can I access RATES Reports data? [not an issue per se, just a question]

### ISSUE THREAD

**Issue by arrowstem** [shbatm/PyISY#24]
Hello,

in my ISY Portal page, I can select RATES Reports from the menu 

![isy_screenshot1](https://user-images.githubusercontent.com/25650836/79710396-dc3c5900-8292-11ea-8f31-824cab9ca1d1.jpg)

and view a table with many useful parameters. How can I access them using PyISY? I'm especially interested in Facility kWh and Inside (Temperature), but other parameters would be also nice to get.
 
![isy_screenshot2](https://user-images.githubusercontent.com/25650836/79710278-85368400-8292-11ea-96cd-ee4bb6404f6e.jpg)

**Comment by shbatm** [comment]
@mkohanim - I figured it would be easier to ask the source... Is this information accessible outside of the Portal (e.g. via REST or SOAP)?

**Comment by shbatm** [comment]
@arrowstem  --- Closing this on here for now. I would reach out on the ISY forum to see if there's a way to get this data from REST.
