### ISSUE TITLE
Insteon events aren't working or aren't working reliably.

### ISSUE THREAD

**Issue by shbatm** [shbatm/PyISY#3]
From @rccoleman:
Specifically, I have motion sensors and wall switches that send events and they no longer trigger my Hass automations with your branch, while they work immediately when I switch back to my branch. I haven't spent time digging into what's wrong, but it's definitely not working.

**Comment by shbatm** [comment]
@rccoleman I made some changes to the core ISY platform for Hass when I implemented the event changes here and added the climate module.

I will troubleshoot the backwards compatibility, but if you are interested in further testing, you can add my ISY platform as a `custom-component` in Hass (add [this folder]() to `config/custom-component/`

**Comment by rccoleman** [comment]
Ok, I'll check it out.
