### ISSUE TITLE
Multi Status device information

### ISSUE THREAD

**Issue by simplextech** [shbatm/PyISY#6]
Is it possible to get/subscribe to the multisensor and multi-level device information?

an example of a multi-sensor being a Zooz 4-in-1 sensor that also provides temperature, humidity, luminance.  a node for motion sensor is created within the ISY and a node for multisensor.  The motion node provides the correct ST value, uom and prec.  However the multisensor node provides nothing in REST.  

The same applies for energy meter devices (power plugs) they have the watts available but total watts used that displays in admin console doesn't seem to be available anywhere.

I'm curious how this information is being pulled for use within Home Assistant through PyISY?

**Comment by shbatm** [comment]
These should be working in the latest PyISY_beta version and Home Assistant HACS version of ISY. 

When you pull the initial information from REST the attributes don't appear, but as soon as you connect to the websocket event stream the ISY dumps all of the values to the stream. This module now listens for any "new" components and adds them as attributes (you can also get them by individually calling the nodes via REST, but this is a lot more resource intensive) 

To use them in Home Assistant, it's best to create template sensors for each attribute that you want to have as a stand alone sensor. 

See this post/thread https://community.home-assistant.io/t/isy994-z-wave-sensor-enhancements-testers-wanted/124188/81?u=shbatm

**Comment by simplextech** [comment]
I'm not using Home Assistant.  I'm using the PyIS-Beta directly as I'm working on a ISY Nodeserver to connect an ISY to an ISY for a Z-Wave device mirror.  It's great all the work going into PyISY however the direction being centered around Home Assistant is leaving out every other use case.

How can the extended property information be accessed directly from PyISY?

**Comment by shbatm** [comment]
Once you've connected to the event stream (i.e. by setting `isy.auto_update = True` after initializing and connecting) they should be populated in the `node.aux_properties` dict for each node available in `isy.nodes`.  They will not be available right away, it takes a few seconds to populate everything if you have a large ISY network.  

You can react when they are populated by subscribing to the individual control events for the nodes that you are interested in:

```python
        """Subscribe to the node change events."""
        self._change_handler = self._node.status.subscribe("changed", self.on_update)

        if hasattr(self._node, "controlEvents"):
            self._control_handler = self._node.controlEvents.subscribe(self.on_control)
```

I know you're not using Home Assistant, but [this](https://github.com/shbatm/hacs-isy994/tree/master/custom_components/isy994) is the specific code section that handles these kind of events.  If you're good at following code around, you can probably glean more details from here.  Specifically, extracting and managing `aux_properties` are handled around Lines [565](https://github.com/shbatm/hacs-isy994/blob/85edf905d329ba849ef735f6b1c371afbca5b022/custom_components/isy994/__init__.py#L565) and [627](https://github.com/shbatm/hacs-isy994/blob/85edf905d329ba849ef735f6b1c371afbca5b022/custom_components/isy994/__init__.py#L627).

I hope that helps. And sorry, I know most of these changes are HA-centric, but I've been trying to keep anything in this beta HA agnostic and make sure I'm not doing anything in the HA code that would be better served for the broader ISY audience in this module.  If you find anything that you're seeing lacking, please let me know.

**Comment by simplextech** [comment]
Thanks for the leads.  I'm using 'aux_properties' and all I get back is an empty dict

> 2019-09-11 20:41:11,600 [Thread-6  ] [INFO ] Notification Received
> 2019-09-11 20:41:11,601 [Thread-6  ] [INFO ] Updating Driver zw021_143 - ST: 2.380, uom: 73
> 2019-09-11 20:41:11,606 [Thread-6  ] [DEBUG] Node:
> 2019-09-11 20:41:11,607 [Thread-6  ] [DEBUG] ZW021_143
> 2019-09-11 20:41:11,609 [Thread-6  ] [DEBUG] {}

`        for name, val in self.isy.nodes[nid].aux_properties.items():
            v = val.get("value")
            uom = val.get("uom", None)
            prec = val.get("prec")
            print(v, uom, prec)`

**Comment by simplextech** [comment]
Worked it out so far.  Thanks for your code as I wasn't aware of and did not have self._node.controlEvents.subscribe setup.  After looking through the HASS pieces you sent me I saw the problem and I've added the missing piece.  A Power plug is working well now.  Time to move on to a Thermostat :)
